import React from 'react';

export default function SettingsPage({ settings, setSettings, championships, onLandingPage, timezoneLabel }) {
  return <section className="settings-page">
    <header className="page-heading settings-page-heading"><div><p className="eyebrow accent">Preferences <span className="heading-rule" /></p><h1>Settings</h1></div></header>
    <div className="settings-groups">
      <section className="settings-group"><div><p className="eyebrow accent">Startup</p><h2>Landing page</h2></div><label className="settings-field"><span>Open on</span><select value={settings.landingPage === 'calendar' || !championships.includes(settings.landingPage) ? championships[0] ?? 'week' : settings.landingPage} onChange={(event) => onLandingPage(event.target.value)}><option value="week">This week</option>{championships.map((item) => <option value={item} key={item}>{item}</option>)}</select></label></section>
      <section className="settings-group"><div><p className="eyebrow accent">Display</p><h2>Date &amp; time</h2></div><label className="settings-field"><span>Format</span><select value={settings.dateTimeFormat} onChange={(event) => setSettings((current) => ({ ...current, dateTimeFormat: event.target.value }))}><option value="auto">Automatic</option><option value="manual">Manual override</option></select></label>{settings.dateTimeFormat === 'manual' && <><label className="settings-field"><span>Date order</span><select value={settings.dateStyle} onChange={(event) => setSettings((current) => ({ ...current, dateStyle: event.target.value }))}><option value="dmy">DD / MM / YYYY</option><option value="mdy">MM / DD / YYYY</option><option value="ymd">YYYY / MM / DD</option></select></label><label className="settings-field"><span>Clock</span><select value={settings.timeStyle} onChange={(event) => setSettings((current) => ({ ...current, timeStyle: event.target.value }))}><option value="12">12-hour</option><option value="24">24-hour</option></select></label></>}</section>
      <section className="settings-group"><div><p className="eyebrow accent">Time</p><h2>Timezone</h2></div><label className="settings-field"><span>Timezone</span><select value={settings.timezoneMode} onChange={(event) => setSettings((current) => ({ ...current, timezoneMode: event.target.value }))}><option value="auto">Automatic ({timezoneLabel})</option><option value="manual">Manual override</option></select></label>{settings.timezoneMode === 'manual' && <label className="settings-field"><span>IANA timezone</span><input value={settings.manualTimezone} onChange={(event) => setSettings((current) => ({ ...current, manualTimezone: event.target.value }))} placeholder="Europe/Paris" list="timezone-suggestions" /><datalist id="timezone-suggestions"><option value="UTC" /><option value="America/New_York" /><option value="America/Chicago" /><option value="America/Denver" /><option value="America/Los_Angeles" /><option value="Europe/London" /><option value="Europe/Paris" /><option value="Asia/Tokyo" /><option value="Australia/Sydney" /></datalist></label>}</section>
    </div>
  </section>;
}
